/**
 * Message entity interface
 * Represents an internationalization message (IDS) from GRD/GRDP files
 */
export interface IMessage {
  /** Primary key */
  id?: number;

  /** Message name (e.g., 'IDS_APP_NAME') */
  name: string;

  /** English text (presentable text generated by GRIT algorithm) */
  english: string;

  /** Meaning attribute (optional, used for hash calculation) */
  meaning?: string;

  /** Message description (optional) */
  description?: string;

  /** Hash ID calculated by GRIT algorithm (decimal string) */
  id_hash: string;

  /** Source GRD file path (if defined in GRD) */
  grd_path?: string;

  /** Source GRDP file path (if defined in GRDP) */
  grdp_path?: string;

  /** Start line number in source file */
  start_line?: number;

  /** End line number in source file */
  end_line?: number;

  /** Presentable text (for debugging, same as english) */
  presentable_text?: string;

  /** Placeholder/ICU-preserving source text for translation prompts (not stored in DB) */
  source_text?: string;
}

/**
 * Message with translations joined
 * Used for displaying complete translation information
 */
export interface IMessageWithTranslations extends IMessage {
  /** All translations for this message */
  translations: ITranslation[];
}

/**
 * Import translation interface for reference
 */
import { ITranslation } from './translation';
